name: Hola_Mundo
run-name: Estoy aprendiendo GitHub Actions!
on: [push]
jobs:
  Hola_Mun2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Make script executable
        run: chmod +x ./holamundo.sh   
        
      - name: Run a one-line script
        run: ./hola-mundo.yml
